import {
  nutrientBand,
  pointNutrient,
  type NutritionProfile,
  type NutritionSource,
} from "./types";

export const LOCAL_DATA_NOTICE =
  "KcalCue 參考營養資料；密度範圍來自公開資料及已記錄的烹調不確定性規則，並非此餐的化驗結果。";

const USDA_ATTRIBUTION =
  "U.S. Department of Agriculture, FoodData Central（公有領域／CC0）。KcalCue 對烹調不確定性套用已記錄的密度範圍。";

function usdaSource(sourceId: string, sourceName: string): NutritionSource {
  return {
    provider: "kcalcue-reference",
    sourceId,
    sourceName,
    attribution: USDA_ATTRIBUTION,
  };
}

function pointMacros(
  calories: number,
  protein: number,
  carbs: number,
  fat: number,
) {
  return {
    calories: pointNutrient(calories),
    protein: pointNutrient(protein),
    carbs: pointNutrient(carbs),
    fat: pointNutrient(fat),
  };
}

export const localNutritionProfiles: NutritionProfile[] = [
  {
    id: "white-rice-cooked",
    displayName: "白飯",
    canonicalName: "rice",
    category: "rice",
    preparations: ["steamed", "boiled", "cooked"],
    aliases: ["white rice", "cooked white rice", "rice", "白飯", "米飯"],
    composite: false,
    nutrientsPer100g: pointMacros(130, 2.7, 28.2, 0.3),
    gramsPerUnit: { g: 1, bowl: 200, cup: 186 },
    source: usdaSource("sr-legacy:rice-white-cooked", "USDA SR Legacy：白米飯（熟）"),
    dataNotice: LOCAL_DATA_NOTICE,
    densityBasis: "單一公開熟白米參考值；水分差異已由份量範圍表達。",
  },
  {
    id: "rice-cooked-mixed",
    displayName: "熟飯（紅米／糙米混合）",
    canonicalName: "rice",
    category: "rice",
    preparations: ["steamed", "boiled", "cooked"],
    aliases: ["brown rice", "red rice", "mixed rice", "紅米飯", "糙米飯"],
    composite: false,
    nutrientsPer100g: nutrientBand([118, 138], [2.4, 2.9], [24.5, 29], [0.3, 1.1]),
    gramsPerUnit: { g: 1, bowl: 200, cup: 186 },
    source: usdaSource(
      "sr-legacy:rice-cooked-white-brown",
      "USDA SR Legacy：白米飯／糙米飯（熟）組合範圍",
    ),
    dataNotice: LOCAL_DATA_NOTICE,
    densityBasis:
      "下限接近熟糙米／紅米，上限接近熟白米；相片無法確認米種比例與含水量。",
  },
  {
    id: "chicken-thigh-grilled",
    displayName: "烤雞扒",
    canonicalName: "chicken-thigh",
    category: "poultry",
    preparations: ["grilled", "pan_fried", "cooked"],
    aliases: [
      "grilled chicken thigh",
      "chicken thigh",
      "chicken steak",
      "chicken",
      "雞扒",
      "雞腿",
      "烤雞扒",
    ],
    composite: false,
    nutrientsPer100g: nutrientBand([200, 250], [22, 27], [0, 1], [11, 17]),
    gramsPerUnit: { g: 1, piece: 150 },
    source: usdaSource(
      "sr-legacy:chicken-thigh-cooked",
      "USDA SR Legacy：熟雞腿肉，並加入煎烤用油不確定性",
    ),
    dataNotice: LOCAL_DATA_NOTICE,
    densityBasis: "熟雞腿公開值為中位；上下限反映連皮／去皮及煎烤吸油差異。",
  },
  {
    id: "chicken-breast-cooked",
    displayName: "熟雞胸肉",
    canonicalName: "chicken-breast",
    category: "poultry",
    preparations: ["grilled", "pan_fried", "cooked", "steamed"],
    aliases: [
      "chicken breast",
      "grilled chicken breast",
      "pan-seared chicken breast",
      "雞胸",
      "雞胸肉",
    ],
    composite: false,
    nutrientsPer100g: nutrientBand([151, 210], [28, 32], [0, 1.5], [3.2, 10]),
    gramsPerUnit: { g: 1, piece: 140 },
    source: usdaSource(
      "sr-legacy:chicken-breast-cooked",
      "USDA SR Legacy：熟雞胸（去皮）＋煎煮吸油範圍",
    ),
    dataNotice: LOCAL_DATA_NOTICE,
    densityBasis:
      "下限為去皮烤／烚雞胸公開值；上限加入香煎用油及輕微醃料碳水化合物。",
  },
  {
    id: "leafy-greens-cooked",
    displayName: "熟青菜",
    canonicalName: "leafy-greens",
    category: "vegetable",
    preparations: ["steamed", "boiled", "cooked", "stir_fried"],
    aliases: [
      "cooked leafy greens",
      "leafy vegetables",
      "bok choy",
      "vegetables",
      "青菜",
      "菜心",
      "白菜",
      "熟青菜",
    ],
    composite: false,
    nutrientsPer100g: nutrientBand([16, 45], [1.4, 2.4], [2.4, 5], [0.2, 3.2]),
    gramsPerUnit: { g: 1, bowl: 160, cup: 150 },
    source: usdaSource(
      "sr-legacy:leafy-greens-cooked",
      "USDA：熟葉菜；炒製時加入食油密度範圍",
    ),
    dataNotice: LOCAL_DATA_NOTICE,
    densityBasis: "清炒／烚菜接近下限；加油炒製接近上限。",
  },
  {
    id: "mixed-vegetables-stir-fried",
    displayName: "炒什錦蔬菜",
    canonicalName: "mixed-vegetables",
    category: "vegetable",
    preparations: ["stir_fried", "cooked"],
    aliases: ["mixed vegetables", "stir-fried vegetables", "什錦蔬菜", "雜菜"],
    composite: false,
    nutrientsPer100g: nutrientBand([40, 95], [1.5, 3.2], [6, 12], [0.4, 6.5]),
    gramsPerUnit: { g: 1, bowl: 160, cup: 150 },
    source: usdaSource(
      "sr-legacy:mixed-vegetables-cooked",
      "USDA：熟什錦蔬菜＋炒製吸油範圍",
    ),
    dataNotice: LOCAL_DATA_NOTICE,
    densityBasis: "混合蔬菜公開熟食值為下限附近；炒鑊吸油把脂肪與熱量拉闊。",
  },
  {
    id: "savory-sauce",
    displayName: "醬汁",
    canonicalName: "sauce",
    category: "sauce",
    preparations: ["sauced", "cooked", "unknown"],
    aliases: ["savory sauce", "sauce", "gravy", "豉油汁", "醬汁"],
    composite: false,
    nutrientsPer100g: nutrientBand([80, 220], [1, 3], [6, 18], [4, 18]),
    gramsPerUnit: { g: 1, ml: 1.05, cup: 250 },
    source: usdaSource("sr-legacy:savory-sauce-generic", "通用鹹味醬汁參考範圍"),
    dataNotice: LOCAL_DATA_NOTICE,
    densityBasis: "糖、油、澱粉增稠都會大幅改變醬汁密度，因此使用寬範圍。",
  },
  {
    id: "tomato-sauce",
    displayName: "番茄醬汁",
    canonicalName: "tomato-sauce",
    category: "sauce",
    preparations: ["sauced", "cooked", "unknown"],
    aliases: ["tomato sauce", "tomato-based sauce", "番茄醬", "茄汁"],
    composite: false,
    nutrientsPer100g: nutrientBand([24, 75], [0.8, 2], [4, 12], [0.2, 5]),
    gramsPerUnit: { g: 1, ml: 1.04, cup: 245 },
    source: usdaSource(
      "sr-legacy:tomato-sauce",
      "USDA：番茄醬／意式紅醬公開值範圍",
    ),
    dataNotice: LOCAL_DATA_NOTICE,
    densityBasis: "原味番茄醬接近下限；加油、糖或奶油的餐廳醬接近上限。",
  },
  {
    id: "egg-boiled",
    displayName: "雞蛋",
    canonicalName: "egg",
    category: "egg",
    preparations: ["boiled", "pan_fried", "cooked"],
    aliases: ["egg", "boiled egg", "fried egg", "雞蛋", "煎蛋", "烚蛋"],
    composite: false,
    nutrientsPer100g: nutrientBand([143, 196], [12, 13.6], [0.7, 1.4], [9.5, 15]),
    gramsPerUnit: { g: 1, piece: 50 },
    source: usdaSource("sr-legacy:egg-cooked", "USDA：全蛋；煎蛋加入用油範圍"),
    dataNotice: LOCAL_DATA_NOTICE,
    densityBasis: "烚蛋接近下限；煎蛋因用油提高脂肪與熱量。",
  },
  {
    id: "noodles-cooked",
    displayName: "熟麵",
    canonicalName: "noodles",
    category: "noodles",
    preparations: ["boiled", "cooked"],
    aliases: ["noodles", "cooked noodles", "egg noodles", "麵", "麵條", "熟麵"],
    composite: false,
    nutrientsPer100g: pointMacros(138, 4.5, 25, 2.1),
    gramsPerUnit: { g: 1, bowl: 250, cup: 160 },
    source: usdaSource("sr-legacy:egg-noodles-cooked", "USDA：熟蛋麵"),
    dataNotice: LOCAL_DATA_NOTICE,
    densityBasis: "以熟麵公開單點值計算；炒麵另屬組合菜式。",
  },
  {
    id: "bread-white",
    displayName: "白麵包",
    canonicalName: "bread",
    category: "bread",
    preparations: ["cooked", "unknown"],
    aliases: ["white bread", "bread", "toast", "白麵包", "方包", "多士"],
    composite: false,
    nutrientsPer100g: pointMacros(266, 8.9, 49.4, 3.3),
    gramsPerUnit: { g: 1, piece: 30 },
    source: usdaSource("sr-legacy:bread-white", "USDA：白麵包"),
    dataNotice: LOCAL_DATA_NOTICE,
    densityBasis: "白麵包公開單點值。",
  },
  {
    id: "beef-cooked",
    displayName: "熟牛肉",
    canonicalName: "beef",
    category: "beef",
    preparations: ["grilled", "pan_fried", "cooked"],
    aliases: ["cooked beef", "beef", "steak", "牛肉", "牛扒", "熟牛肉"],
    composite: false,
    nutrientsPer100g: nutrientBand([210, 290], [24, 29], [0, 1], [10, 20]),
    gramsPerUnit: { g: 1, piece: 170 },
    source: usdaSource("sr-legacy:beef-cooked", "USDA：熟牛肉，含肥瘦差異"),
    dataNotice: LOCAL_DATA_NOTICE,
    densityBasis: "瘦切件接近下限；較肥或加油煎的牛扒接近上限。",
  },
  {
    id: "pork-cooked",
    displayName: "熟豬肉",
    canonicalName: "pork",
    category: "pork",
    preparations: ["grilled", "pan_fried", "cooked"],
    aliases: ["cooked pork", "pork", "pork chop", "豬肉", "豬扒", "熟豬肉"],
    composite: false,
    nutrientsPer100g: nutrientBand([200, 280], [24, 29], [0, 1], [10, 19]),
    gramsPerUnit: { g: 1, piece: 160 },
    source: usdaSource("sr-legacy:pork-cooked", "USDA：熟豬肉，含肥瘦差異"),
    dataNotice: LOCAL_DATA_NOTICE,
    densityBasis: "瘦豬扒接近下限；連肥或煎炸接近上限。",
  },
  {
    id: "salmon-cooked",
    displayName: "熟三文魚",
    canonicalName: "salmon",
    category: "seafood",
    preparations: ["grilled", "pan_fried", "cooked"],
    aliases: ["cooked salmon", "salmon", "三文魚", "熟三文魚"],
    composite: false,
    nutrientsPer100g: nutrientBand([179, 230], [20, 25], [0, 0.5], [10, 16]),
    gramsPerUnit: { g: 1, piece: 150 },
    source: usdaSource("sr-legacy:salmon-cooked", "USDA：熟三文魚"),
    dataNotice: LOCAL_DATA_NOTICE,
    densityBasis: "烤魚接近下限；煎魚連皮及用油接近上限。",
  },
  {
    id: "tofu-firm",
    displayName: "豆腐",
    canonicalName: "tofu",
    category: "tofu",
    preparations: ["raw", "cooked", "steamed", "stir_fried"],
    aliases: ["firm tofu", "tofu", "bean curd", "豆腐"],
    composite: false,
    nutrientsPer100g: pointMacros(144, 17, 2.8, 8.7),
    gramsPerUnit: { g: 1, piece: 100, bowl: 200 },
    source: usdaSource("sr-legacy:tofu-firm", "USDA：板豆腐"),
    dataNotice: LOCAL_DATA_NOTICE,
    densityBasis: "板豆腐公開單點值。",
  },
  {
    id: "dumpling-cooked",
    displayName: "餃子",
    canonicalName: "dumpling",
    category: "mixed",
    preparations: ["boiled", "pan_fried", "cooked"],
    aliases: ["dumpling", "dumplings", "gyoza", "餃子", "水餃", "鍋貼"],
    composite: true,
    nutrientsPer100g: nutrientBand([180, 260], [6, 10], [22, 32], [5, 12]),
    gramsPerUnit: { g: 1, piece: 25 },
    source: usdaSource("generic:dumpling", "組合點心通用範圍，非單一配方"),
    dataNotice: LOCAL_DATA_NOTICE,
    densityBasis: "餡料、皮厚及煎／烚差異很大，只提供保守範圍。",
  },
  {
    id: "apple",
    displayName: "蘋果",
    canonicalName: "apple",
    category: "fruit",
    preparations: ["raw", "unknown"],
    aliases: ["apple", "蘋果"],
    composite: false,
    nutrientsPer100g: pointMacros(52, 0.3, 13.8, 0.2),
    gramsPerUnit: { g: 1, piece: 180 },
    source: usdaSource("sr-legacy:apple-raw", "USDA：生蘋果"),
    dataNotice: LOCAL_DATA_NOTICE,
    densityBasis: "生蘋果公開單點值。",
  },
  {
    id: "banana",
    displayName: "香蕉",
    canonicalName: "banana",
    category: "fruit",
    preparations: ["raw", "unknown"],
    aliases: ["banana", "香蕉"],
    composite: false,
    nutrientsPer100g: pointMacros(89, 1.1, 22.8, 0.3),
    gramsPerUnit: { g: 1, piece: 118 },
    source: usdaSource("sr-legacy:banana-raw", "USDA：香蕉"),
    dataNotice: LOCAL_DATA_NOTICE,
    densityBasis: "香蕉公開單點值。",
  },
  {
    id: "whole-milk",
    displayName: "全脂奶",
    canonicalName: "milk",
    category: "dairy",
    preparations: ["raw", "unknown"],
    aliases: ["whole milk", "milk", "牛奶", "全脂奶"],
    composite: false,
    nutrientsPer100g: pointMacros(61, 3.2, 4.8, 3.3),
    gramsPerUnit: { g: 1, ml: 1.03, cup: 244 },
    source: usdaSource("sr-legacy:milk-whole", "USDA：全脂奶"),
    dataNotice: LOCAL_DATA_NOTICE,
    densityBasis: "全脂奶公開單點值。",
  },
  {
    id: "french-fries",
    displayName: "薯條",
    canonicalName: "french-fries",
    category: "fried",
    preparations: ["deep_fried", "cooked"],
    aliases: ["french fries", "fries", "chips", "薯條"],
    composite: false,
    nutrientsPer100g: nutrientBand([270, 340], [3, 4], [36, 44], [12, 18]),
    gramsPerUnit: { g: 1, cup: 117 },
    source: usdaSource("sr-legacy:french-fries", "USDA：炸薯條，含吸油範圍"),
    dataNotice: LOCAL_DATA_NOTICE,
    densityBasis: "餐廳炸爐吸油量差異大，因此使用範圍而不是單一值。",
  },
];
