import type { NutritionProfile } from "./types";

export const LOCAL_DATA_NOTICE =
  "KcalCue 本地示範／參考營養資料；並非即時官方資料。";

export const localNutritionProfiles: NutritionProfile[] = [
  {
    id: "white-rice-cooked",
    displayName: "白飯",
    aliases: ["white rice", "cooked white rice", "rice", "白飯", "米飯"],
    nutrientsPer100g: { calories: 130, protein: 2.7, carbs: 28.2, fat: 0.3 },
    gramsPerUnit: { g: 1, bowl: 200, cup: 186 },
    dataNotice: LOCAL_DATA_NOTICE,
  },
  {
    id: "chicken-thigh-grilled",
    displayName: "烤雞扒",
    aliases: [
      "grilled chicken thigh",
      "chicken thigh",
      "chicken steak",
      "chicken",
      "雞扒",
      "雞腿",
      "烤雞扒",
    ],
    nutrientsPer100g: { calories: 229, protein: 25, carbs: 0, fat: 14 },
    gramsPerUnit: { g: 1, piece: 150 },
    dataNotice: LOCAL_DATA_NOTICE,
  },
  {
    id: "leafy-greens-cooked",
    displayName: "熟青菜",
    aliases: [
      "cooked leafy greens",
      "leafy vegetables",
      "bok choy",
      "vegetables",
      "青菜",
      "菜心",
      "白菜",
      "熟青菜",
    ],
    nutrientsPer100g: { calories: 20, protein: 1.7, carbs: 3.2, fat: 0.2 },
    gramsPerUnit: { g: 1, bowl: 160, cup: 150 },
    dataNotice: LOCAL_DATA_NOTICE,
  },
  {
    id: "savory-sauce",
    displayName: "醬汁",
    aliases: ["savory sauce", "sauce", "gravy", "豉油汁", "醬汁"],
    nutrientsPer100g: { calories: 180, protein: 2, carbs: 12, fat: 14 },
    gramsPerUnit: { g: 1, ml: 1.05, cup: 250 },
    dataNotice: LOCAL_DATA_NOTICE,
  },
  {
    id: "egg-boiled",
    displayName: "雞蛋",
    aliases: ["egg", "boiled egg", "fried egg", "雞蛋", "煎蛋", "烚蛋"],
    nutrientsPer100g: { calories: 155, protein: 12.6, carbs: 1.1, fat: 10.6 },
    gramsPerUnit: { g: 1, piece: 50 },
    dataNotice: LOCAL_DATA_NOTICE,
  },
  {
    id: "noodles-cooked",
    displayName: "熟麵",
    aliases: ["noodles", "cooked noodles", "egg noodles", "麵", "麵條", "熟麵"],
    nutrientsPer100g: { calories: 138, protein: 4.5, carbs: 25, fat: 2.1 },
    gramsPerUnit: { g: 1, bowl: 250, cup: 160 },
    dataNotice: LOCAL_DATA_NOTICE,
  },
  {
    id: "bread-white",
    displayName: "白麵包",
    aliases: ["white bread", "bread", "toast", "白麵包", "方包", "多士"],
    nutrientsPer100g: { calories: 266, protein: 8.9, carbs: 49.4, fat: 3.3 },
    gramsPerUnit: { g: 1, piece: 30 },
    dataNotice: LOCAL_DATA_NOTICE,
  },
  {
    id: "beef-cooked",
    displayName: "熟牛肉",
    aliases: ["cooked beef", "beef", "steak", "牛肉", "牛扒", "熟牛肉"],
    nutrientsPer100g: { calories: 250, protein: 26, carbs: 0, fat: 15 },
    gramsPerUnit: { g: 1, piece: 170 },
    dataNotice: LOCAL_DATA_NOTICE,
  },
  {
    id: "pork-cooked",
    displayName: "熟豬肉",
    aliases: ["cooked pork", "pork", "pork chop", "豬肉", "豬扒", "熟豬肉"],
    nutrientsPer100g: { calories: 242, protein: 27, carbs: 0, fat: 14 },
    gramsPerUnit: { g: 1, piece: 160 },
    dataNotice: LOCAL_DATA_NOTICE,
  },
  {
    id: "salmon-cooked",
    displayName: "熟三文魚",
    aliases: ["cooked salmon", "salmon", "三文魚", "熟三文魚"],
    nutrientsPer100g: { calories: 206, protein: 22, carbs: 0, fat: 12 },
    gramsPerUnit: { g: 1, piece: 150 },
    dataNotice: LOCAL_DATA_NOTICE,
  },
  {
    id: "tofu-firm",
    displayName: "豆腐",
    aliases: ["firm tofu", "tofu", "bean curd", "豆腐"],
    nutrientsPer100g: { calories: 144, protein: 17, carbs: 2.8, fat: 8.7 },
    gramsPerUnit: { g: 1, piece: 100, bowl: 200 },
    dataNotice: LOCAL_DATA_NOTICE,
  },
  {
    id: "dumpling-cooked",
    displayName: "餃子",
    aliases: ["dumpling", "dumplings", "gyoza", "餃子", "水餃", "鍋貼"],
    nutrientsPer100g: { calories: 210, protein: 8, carbs: 28, fat: 7 },
    gramsPerUnit: { g: 1, piece: 25 },
    dataNotice: LOCAL_DATA_NOTICE,
  },
  {
    id: "apple",
    displayName: "蘋果",
    aliases: ["apple", "蘋果"],
    nutrientsPer100g: { calories: 52, protein: 0.3, carbs: 13.8, fat: 0.2 },
    gramsPerUnit: { g: 1, piece: 180 },
    dataNotice: LOCAL_DATA_NOTICE,
  },
  {
    id: "banana",
    displayName: "香蕉",
    aliases: ["banana", "香蕉"],
    nutrientsPer100g: { calories: 89, protein: 1.1, carbs: 22.8, fat: 0.3 },
    gramsPerUnit: { g: 1, piece: 118 },
    dataNotice: LOCAL_DATA_NOTICE,
  },
  {
    id: "whole-milk",
    displayName: "全脂奶",
    aliases: ["whole milk", "milk", "牛奶", "全脂奶"],
    nutrientsPer100g: { calories: 61, protein: 3.2, carbs: 4.8, fat: 3.3 },
    gramsPerUnit: { g: 1, ml: 1.03, cup: 244 },
    dataNotice: LOCAL_DATA_NOTICE,
  },
  {
    id: "french-fries",
    displayName: "薯條",
    aliases: ["french fries", "fries", "chips", "薯條"],
    nutrientsPer100g: { calories: 312, protein: 3.4, carbs: 41, fat: 15 },
    gramsPerUnit: { g: 1, cup: 117 },
    dataNotice: LOCAL_DATA_NOTICE,
  },
];
